---
title: "Word2Vec analyses"
output: html_notebook
---
```{r}
library(tidyverse)
library(glmnet)
library(glmnetUtils)
```

```{r}
setwd("/Users/kushin/Documents/Github/semantic_spaces/analysis")
df = read.csv('../data/reg_df.csv')
```


```{r}
col_rating_cols = colnames(df)[2:59]
w2v_cols = colnames(df)[63:length(colnames(df))]
pc_cols = colnames(df)[60:62]

holdout_rows = seq(from=1,to=30,by=5)

```


```{r}
c1_model = cv.glmnet(as.matrix(df[!(rownames(df)%in%holdout_rows),w2v_cols]),as.matrix(df[!(rownames(df)%in%holdout_rows),pc_cols][1]))
c2_model = cv.glmnet(as.matrix(df[!(rownames(df)%in%holdout_rows),w2v_cols]),as.matrix(df[!(rownames(df)%in%holdout_rows),pc_cols][2]))
c3_model = cv.glmnet(as.matrix(df[!(rownames(df)%in%holdout_rows),w2v_cols]),as.matrix(df[!(rownames(df)%in%holdout_rows),pc_cols][3]))
plot(c1_model)
plot(c2_model)
plot(c3_model)
print(c1_model)
```

```{r}
library(psych)
coef(c1_model,s='lambda.min')



p = predict(c1_model, newx = as.matrix(df[(rownames(df)%in%holdout_rows),w2v_cols]), s = "lambda.min")
t = df[(rownames(df)%in%holdout_rows),pc_cols][1]

cor(p,t)
print(psych::corr.test(p,t),short=F)
```

